// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: declvol/v1/declvol.proto

#include "declvol/v1/declvol.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace declvol {
namespace v1 {
PROTOBUF_CONSTEXPR SwitchProfileRequest::SwitchProfileRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.profile_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.config_path_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SwitchProfileRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SwitchProfileRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SwitchProfileRequestDefaultTypeInternal() {}
  union {
    SwitchProfileRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SwitchProfileRequestDefaultTypeInternal _SwitchProfileRequest_default_instance_;
PROTOBUF_CONSTEXPR SwitchProfileResponse::SwitchProfileResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._cached_size_)*/{}} {}
struct SwitchProfileResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SwitchProfileResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SwitchProfileResponseDefaultTypeInternal() {}
  union {
    SwitchProfileResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SwitchProfileResponseDefaultTypeInternal _SwitchProfileResponse_default_instance_;
}  // namespace v1
}  // namespace declvol
namespace declvol {
namespace v1 {

// ===================================================================

class SwitchProfileRequest::_Internal {
 public:
};

SwitchProfileRequest::SwitchProfileRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:declvol.v1.SwitchProfileRequest)
}
SwitchProfileRequest::SwitchProfileRequest(const SwitchProfileRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  SwitchProfileRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.profile_){}
    , decltype(_impl_.config_path_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  _impl_.profile_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.profile_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_profile().empty()) {
    _this->_impl_.profile_.Set(from._internal_profile(), 
      _this->GetArenaForAllocation());
  }
  _impl_.config_path_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.config_path_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_config_path().empty()) {
    _this->_impl_.config_path_.Set(from._internal_config_path(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:declvol.v1.SwitchProfileRequest)
}

inline void SwitchProfileRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.profile_){}
    , decltype(_impl_.config_path_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.profile_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.profile_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.config_path_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.config_path_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

SwitchProfileRequest::~SwitchProfileRequest() {
  // @@protoc_insertion_point(destructor:declvol.v1.SwitchProfileRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SwitchProfileRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.profile_.Destroy();
  _impl_.config_path_.Destroy();
}

void SwitchProfileRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SwitchProfileRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:declvol.v1.SwitchProfileRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.profile_.ClearToEmpty();
  _impl_.config_path_.ClearToEmpty();
  _internal_metadata_.Clear<std::string>();
}

const char* SwitchProfileRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string profile = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_profile();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, nullptr));
        } else
          goto handle_unusual;
        continue;
      // string config_path = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_config_path();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, nullptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SwitchProfileRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:declvol.v1.SwitchProfileRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string profile = 1;
  if (!this->_internal_profile().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_profile().data(), static_cast<int>(this->_internal_profile().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "declvol.v1.SwitchProfileRequest.profile");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_profile(), target);
  }

  // string config_path = 2;
  if (!this->_internal_config_path().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_config_path().data(), static_cast<int>(this->_internal_config_path().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "declvol.v1.SwitchProfileRequest.config_path");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_config_path(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:declvol.v1.SwitchProfileRequest)
  return target;
}

size_t SwitchProfileRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:declvol.v1.SwitchProfileRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string profile = 1;
  if (!this->_internal_profile().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_profile());
  }

  // string config_path = 2;
  if (!this->_internal_config_path().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_config_path());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SwitchProfileRequest::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const SwitchProfileRequest*>(
      &from));
}

void SwitchProfileRequest::MergeFrom(const SwitchProfileRequest& from) {
  SwitchProfileRequest* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:declvol.v1.SwitchProfileRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_profile().empty()) {
    _this->_internal_set_profile(from._internal_profile());
  }
  if (!from._internal_config_path().empty()) {
    _this->_internal_set_config_path(from._internal_config_path());
  }
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void SwitchProfileRequest::CopyFrom(const SwitchProfileRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:declvol.v1.SwitchProfileRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SwitchProfileRequest::IsInitialized() const {
  return true;
}

void SwitchProfileRequest::InternalSwap(SwitchProfileRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.profile_, lhs_arena,
      &other->_impl_.profile_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.config_path_, lhs_arena,
      &other->_impl_.config_path_, rhs_arena
  );
}

std::string SwitchProfileRequest::GetTypeName() const {
  return "declvol.v1.SwitchProfileRequest";
}


// ===================================================================

class SwitchProfileResponse::_Internal {
 public:
};

SwitchProfileResponse::SwitchProfileResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:declvol.v1.SwitchProfileResponse)
}
SwitchProfileResponse::SwitchProfileResponse(const SwitchProfileResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  SwitchProfileResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:declvol.v1.SwitchProfileResponse)
}

inline void SwitchProfileResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      /*decltype(_impl_._cached_size_)*/{}
  };
}

SwitchProfileResponse::~SwitchProfileResponse() {
  // @@protoc_insertion_point(destructor:declvol.v1.SwitchProfileResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SwitchProfileResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void SwitchProfileResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SwitchProfileResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:declvol.v1.SwitchProfileResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear<std::string>();
}

const char* SwitchProfileResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SwitchProfileResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:declvol.v1.SwitchProfileResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:declvol.v1.SwitchProfileResponse)
  return target;
}

size_t SwitchProfileResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:declvol.v1.SwitchProfileResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SwitchProfileResponse::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const SwitchProfileResponse*>(
      &from));
}

void SwitchProfileResponse::MergeFrom(const SwitchProfileResponse& from) {
  SwitchProfileResponse* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:declvol.v1.SwitchProfileResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void SwitchProfileResponse::CopyFrom(const SwitchProfileResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:declvol.v1.SwitchProfileResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SwitchProfileResponse::IsInitialized() const {
  return true;
}

void SwitchProfileResponse::InternalSwap(SwitchProfileResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
}

std::string SwitchProfileResponse::GetTypeName() const {
  return "declvol.v1.SwitchProfileResponse";
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace declvol
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::declvol::v1::SwitchProfileRequest*
Arena::CreateMaybeMessage< ::declvol::v1::SwitchProfileRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::declvol::v1::SwitchProfileRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::declvol::v1::SwitchProfileResponse*
Arena::CreateMaybeMessage< ::declvol::v1::SwitchProfileResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::declvol::v1::SwitchProfileResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
